Update PublishNugate.yml

diff --git a/.github/workflows/PublishNugate.yml b/.github/workflows/PublishNugate.yml
--- a/.github/workflows/PublishNugate.yml
+++ b/.github/workflows/PublishNugate.yml
@@ -89,10 +89,10 @@ jobs:
         env:
          SUPER_SECRET: ${{ secrets.NUGET_SECRET_KEY }}
         run: |
-          echo "Length of NuGet Secret Key from secret: ${{ secrets.NUGET_SECRET_KEY }}"
+          echo "Length of NuGet Secret Key from secret: ${#SUPER_SECRET}"
           for file in ${{ env.NuGetDirectory }}/*.nupkg; do
-            dotnet nuget push "$file" --api-key "${{ secrets.NUGET_SECRET_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate || {
-             echo "Failed to push $file"
-             exit 1
-          }
+            dotnet nuget push "$file" --api-key "$SUPER_SECRET" --source https://api.nuget.org/v3/index.json --skip-duplicate || {
+              echo "Failed to push $file"
+              exit 1
+            }
           done
